export const UPDATE_NEW_PROVIDER_COMMON_NAME = "UUPDATE_PROVIDER_COMMON_NAME";
export const UPDATE_NEW_PROVIDER_FORMAL_NAME =
  "UPDATE_NEW_PROVIDER_FORMAL_NAME";
export const UPDATE_NEW_PROVIDER_EMAIL = "UPDATE_NEW_PROVIDER_EMAIL";
export const UPDATE_NEW_PROVIDER_USAGE_INSTRUCTIONS =
  "UPDATE_NEW_PROVIDER_USAGE_INSTRUCTIONS";
export const BEGIN_SUBMITTING_NEW_PROVIDER = "BEGIN_SUBMITTING_NEW_PROVIDER";
export const SUBMITTED_NEW_PROVIDER = "SUBMITTED_NEW_PROVIDER";
export const UPDATE_PROVIDERS = "UPDATE_PROVIDERS";

export const BEGIN_DELETE_PROVIDER = "BEGIN_DELETE_PROVIDER";
export const DELETE_PROVIDER = "DELETE_PROVIDER";
